image: python:3.11

pipelines:
  default:
    - step:
        name: Deploy to Elastic Beanstalk
        script:
          - apt-get update && apt-get install -y unzip curl

          # Install packaging module manually
          - pip install --upgrade pip
          - pip install packaging

          # Install EB CLI
          - pip install awsebcli --upgrade

          # Install Node.js and npm
          - curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
          - apt-get install -y nodejs

          # Install Node dependencies
          - npm install

          # Initialize and deploy
          - eb init test --region us-west-2 --platform "Node.js 22"
          - eb deploy
